### ISSUE TITLE
superuser and /storage/emulated/0

### ISSUE THREAD

**Issue by MartinRo** [koush/Superuser#170]
Hi koush,
Amazing work @superuser, thanks for that.
I build it Into my Custom Rom 4.3 (JSS15J) rom for the mako and it's working fine with one exception: it seems as if access to /storage/emulated/0 with TitaniumBackup and Root Explorer is broken. When changing to /storage/emulated/legacy Everything is working.
It's not only reported in my rom but also @PA for instant.

Hope you can hell.

**Comment by MartinRo** [comment]
Lol, hell=help ... Crazy auto correction

**Comment by ogr3** [comment]
/storage/sdcard0 also works. I'd appreciate some input on what is the best path on Android 4.3.

**Comment by koush** [comment]
Use the environment variable EMULATED_STORAGE_SOURCE.

I didn't even need to update ROM Manager for the 4.3 update. Using this variable has worked fine for me in 4.1 and beyond.

**Comment by ogr3** [comment]
EMULATED_STORAGE_SOURCE is set to /mnt/shell/emulated on Nexus 4. that path is not accessible by TitaniumBackup trying to browse there. There is another variable called EXTERNAL_STORAGE that resolves to /storage/emulated/legacy

the latter works.

Any thoughts?

**Comment by koush** [comment]
Sec, let me double check on Stock nexus 4.

**Comment by koush** [comment]
Works fine here.

```
MacBook:builder[master*]$ adb shell
shell@mako:/ $ su
root@mako:/ # ls $EMULATED_STORAGE_SOURCE
ls $EMULATED_STORAGE_SOURCE
0
clockworkmod
legacy
obb
superuser.zip
root@mako:/ # 
```

**Comment by koush** [comment]
I just verified that the backups are visible in ROM Manager as well.

**Comment by koush** [comment]
I wonder if Titanium is not listing the directory contents as root. That may be why.

Or it is using hard coded paths of some sort. No idea though.

**Comment by ogr3** [comment]
Difference if the shell is not running as root?

If I try to browse there from within Titanium it can't get past /mnt/shell.

/storage/emulated/legacy works (which is a symlink to /mnt/shell/emulated/0) 

So maybe it's OK once you set the full path, but titanium lets the user browse for the location and that fails going that route. 

They want to store the files to the external SD-card, so maybe EXTERNAL_STORAGE would be better for titanium?

**Comment by koush** [comment]
I think Titanium is not browsing as root if it can't get past /mnt/shell?

**Comment by koush** [comment]
In any case, I really can't say what the Titanium dev is doing. It's understood that platform changes will break apps that use hidden/non-standard/extended APIs or root capabilities. It's really up to him to fix it... I will not put in workarounds or hacks to fix Titanium or any other app.

This has happened before with the multiuser change in 4.1 (/sdcard/0) and the emulated storage introduction (/data/media) way back when. And I'm sure it will happen again in the future.

**Comment by koush** [comment]
He's welcome to join the conversation here and bring up any issues though. If there's actually a bug in Superuser (natural platform breakage/changes aside), I can take a look.

**Comment by FrozenCow** [comment]
I'm sorry to reply on such an old topic, but this seems related to a problem I'm seeing.
DriveDroid is an app that uses root to host images stored on the phone toward a PC over USB (using the USB Mass Storage gadget). Over the last number of months I've received reports from users that hosting images would result in 'Permission Denied'. This was strange since the kernel accesses the file, whereas the app itself could just access the file without problems.

I've only been able to investigate the issue recently since I only recently acquired an Nexus 5 with Android 4.3+ and with help of other users we've found that /storage/emulated/0 is _not_ available for root nor the kernel, whereas it is available for normal apps.

I've considered workarounds, but it seems everything works fine with SuperSU. Somehow for SuperSU /storage/emulated/0 is available for the kernel, root and normal apps.

**Comment by ronasimi** [comment]
Sorry to comment on an old issue, but since 1/12/2014 CM file manager has been unable to access /storage/emulated/0 as root in my unofficial CM build.  I'm guessing that it's related to merging master branch into CM on that date, due to the Superuser daemon now using zygote.  Is there any way to work around this, or is this the new normal for superuser?  Sorry if it's basically a dupe of @FrozenCow 's comment.

**Comment by FrozenCow** [comment]
I've described a workaround that seems to be working for my app here: https://github.com/koush/Superuser/issues/218#issuecomment-32682372
