### ISSUE TITLE
Failed with the new ART VM in Android 4.4 KitKat

### ISSUE THREAD

**Issue by cedricfung** [koush/Superuser#197]
The su works in adb shell, but in APPs

> D/su      ( 3226): su invoked. 
> E/su      ( 3227): chown (/dev/com.koushikdutta.superuser, 10073, 10073) failed with 1: Operation not permitted 

After disable ART, it works

**Comment by cernekee** [comment]
From what I can tell, with ART enabled, zygote-descended processes are restricted by SELinux but they are no longer subject to the [nosuid mount restriction](http://source.android.com/devices/tech/security/enhancements43.html) on /system.  This creates a situation in which the setuid /system/xbin/su binary decides it is OK to run in "standalone" mode instead of connecting to the daemon, but it is unable to perform privileged operations (chown'ing a directory under /dev owned by root) due to the SELinux access controls.

A quick workaround is to change perms on the binary to force it to always operate as a daemon client:

```
adb shell
su
mount -o rw,remount /system
chmod 0755 /system/xbin/su
reboot
```

If this doesn't work, you could try switching SELinux to permissive mode and see what happens.

Mode 0755 installation will be the default for Android 4.3+ on future CWM Superuser releases; see Bug #194.

**Comment by cedricfung** [comment]
It works by changing the perms on su.

**Comment by cernekee** [comment]
Links to the official fix:

http://review.cyanogenmod.org/#/c/53898/
https://github.com/koush/Superuser/commit/b6b13f2307f5608e6e2278ea6e8f92698aa384cb

The current version on the Play Store (2013/11/15) does not appear to have this change yet (and does not claim to).
